### ISSUE TITLE
测试&线上API地址前缀往往转换成了/weapi导致无法进行代理mock

### ISSUE THREAD

**Issue by Qquanwei** [amibug/nei-chrome-devtools#1]

**Comment by amibug** [comment]
加密接口都会被替换成api接口
Visit: https://github.com/amibug/nei-chrome-devtools/blob/master/src/devtools/index.js#L19

**Comment by Qquanwei** [comment]
但是我开启了之后，发现线上的服务还是请求的旧的接口数据

**Comment by Qquanwei** [comment]
并不是因为/weapi导致，所以关掉issue
